version: "3.9"
services:
  tm_api:
    build: .
    container_name: tm_api
    ports:
      - "8000:8000"
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env.example
    volumes:
      - ./database.sqlite3:/code/database.sqlite3